name: build
on: [push, workflow_dispatch]
jobs:
  b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          git clone --depth 1 https://github.com/RusJJ/AndroidModLoader aml
          cp -r aml/mod ./mod
          $ANDROID_NDK_LATEST_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=jni/Android.mk NDK_APPLICATION_MK=jni/Application.mk
      - uses: actions/upload-artifact@v5
        with: { name: DriftCam, path: libs/arm64-v8a/libDriftCam.so }
